apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: yarinkos/ngnix_confd_demo
        env:
          - name: ENV_NAME
            valueFrom:
              configMapKeyRef:
                name: special-config
                key: team
        ports:
        - containerPort: 80